In [29]:
import pandas as pd
df = pd.read_csv('../Datasets/diabetes_two.csv')

<h1><b><font color="green">
Handling Missing Values

<font color="yellow">
(i) Dropping

In [5]:
#check every cell for null values
df.isnull()

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
516,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
517,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
518,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
519,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [6]:
#count of null values for each column
df.isnull().sum()

Age                   1
Gender                1
Polyuria              0
Polydipsia            0
sudden weight loss    0
weakness              1
Polyphagia            0
Genital thrush        0
visual blurring       0
Itching               0
Irritability          0
delayed healing       0
partial paresis       0
muscle stiffness      0
Alopecia              0
Obesity               0
class                 0
dtype: int64

In [7]:
#dataset information. null count and datatype for each column
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 520 entries, 0 to 519
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 519 non-null    float64
 1   Gender              519 non-null    object
 2   Polyuria            520 non-null    object
 3   Polydipsia          520 non-null    object
 4   sudden weight loss  520 non-null    object
 5   weakness            519 non-null    object
 6   Polyphagia          520 non-null    object
 7   Genital thrush      520 non-null    object
 8   visual blurring     520 non-null    object
 9   Itching             520 non-null    object
 10  Irritability        520 non-null    object
 11  delayed healing     520 non-null    object
 12  partial paresis     520 non-null    object
 13  muscle stiffness    520 non-null    object
 14  Alopecia            520 non-null    object
 15  Obesity             520 non-null    object
 16  class               520 non-null    object
dtypes: float64(1), object(16)
memory usage: 69.2+ KB

In [8]:
#numerical data information
df.describe()

              Age
count  519.000000
mean    49.082852
std     27.104027
min     16.000000
25%     39.000000
50%     48.000000
75%     57.000000
max    600.000000

In [9]:
#creating a copy of df
df1 = df.copy()

In [10]:
#dropping the rows containing null cells
df1.dropna(subset=['Age'], inplace=True)
df1.dropna(subset=['Gender'], inplace=True)
df1.dropna(subset=['weakness'], inplace=True)
#inplace=True makes sure that the modification takes place directly and nothing is returned

In [12]:
#check dataset length changes
print('old size: ',len(df))
print('new size: ',len(df1))

old size:  520
new size:  517

<font color="yellow">
(ii) fill with mean/median/most frequent value

In [23]:
df2 = df.copy()

In [22]:
#calculate mean value for Age column
ageMean = df2['Age'].mean()
#replace null cells with mean value
df2['Age'] = df2['Age'].fillna(ageMean)

In [25]:
#replace with median value
ageMedian = df2['Age'].median()
df2['Age'] = df2['Age'].fillna(ageMedian)

In [26]:
#replace with most frequent value (Gender column)
most_freq = df2['Gender'].mode().iloc[0]
df2['Gender'] = df2['Gender'].fillna(most_freq)

In [27]:
#replace with most frequent value (weakness column)
most_freq = df2['weakness'].mode().iloc[0]
df2['weakness'] = df2['weakness'].fillna(most_freq)

In [28]:
#check null counts for each column
df2.isnull().sum()

Age                   0
Gender                0
Polyuria              0
Polydipsia            0
sudden weight loss    0
weakness              0
Polyphagia            0
Genital thrush        0
visual blurring       0
Itching               0
Irritability          0
delayed healing       0
partial paresis       0
muscle stiffness      0
Alopecia              0
Obesity               0
class                 0
dtype: int64

In [19]:
#fill with most freq. value with lambda programming
# same thing but with lambda programming
df2 = df2.apply(lambda x:x.fillna(x.value_counts().index[0]))